<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>BankingServiceProject</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../BankingServiceRepositoryProject/BankingServiceRepositoryProject.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Refit" />
    </ItemGroup>
</Project>
