services:
  bank-postgres:
    container_name: bank-postgres
    image: postgres:latest
    networks:
      - bank-network
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - bank-pg-data:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
      
  bank-zookeeper:
    container_name: bank-zookeeper
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - bank-network

  bank-kafka:
    container_name: bank-kafka
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: bank-zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:9092,INTERNAL://bank-kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: >
        CheckClosedEvent:1:1,
    depends_on:
      - bank-zookeeper
    networks:
      - bank-network
    volumes:
      - bank-kafka-data:/kafka-data
    ports:
      - '9092:9092'

  bank-kafka-ui:
    container_name: bank-kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - bank-network
    restart: unless-stopped
    depends_on:
      - bank-kafka
    ports:
      - "8082:8080"
    volumes:
      - ./src/BankingServicePresentationLayerProject/Protos:/schemas
    environment:
      kafka.clusters.0.name: bank-kafka
      kafka.clusters.0.bootstrapServers: bank-kafka:9094
      kafka.clusters.0.defaultKeySerde: ProtobufFile
      kafka.clusters.0.defaultValueSerde: ProtobufFile

      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /schemas/

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.CheckClosedEvent: grpc_banking_service.kafka.ClosedCheckKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameForValueByTopic.CheckClosedEvent: grpc_banking_service.kafka.ClosedCheckValue

  mock-banking-provider:
    container_name: mock-banking-provider
    networks:
      - bank-network
    build:
      context: .
      dockerfile: Dockerfile.mockprovider
    ports:
      - "8001:8081"

  banking-service:
    container_name: banking-service
    networks:
      - bank-network
    build:
      context: .
      dockerfile: Dockerfile.service
    ports:
      - "8000:8080"
    environment:
      BankingProviders__Mock__BaseUrl: "http://mock-banking-provider:8081"
      BankingService__WebhookBaseUrl: "http://banking-service:8079/reply"
      Kafka__Host: "bank-kafka:9094"
      MOCK_IDENTITY_TOKEN: "identity-token"
      MOCK_ENCRYPTION: "50dgbqH4InrjIyLeJDEAsOHkOy28K5cNfERguI63tXc="
      POSTGRES_CONNECTION_STRING: "Host=bank-postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres"
      ORDER_SERVICE_IDENTITY_TOKEN: "order-service-identity-token"
    depends_on:
        bank-postgres:
          condition: service_healthy
        bank-kafka:
          condition: service_started

networks:
  bank-network:
    driver: bridge

volumes:
  bank-kafka-data:
  bank-pg-data: